baseURL = "http://blog.lijinchao.com/"
languageCode = "zh"
title = "日拱一卒"
theme = "hugo-theme-learn"

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir= true




[Languages]
[Languages.zh]

[[Languages.zh.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub 仓库"
identifier = "ds"
url = "https://github.com/lijinchao2007"
weight = 10

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 鸣谢"
url = "/credits"
weight = 30
